return {
  -- { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "EdenEast/nightfox.nvim", lazy = false },
  { "Mofiqul/vscode.nvim", lazy = false },
  { "aktersnurra/no-clown-fiesta.nvim" },
  { "chama-chomo/grail" },
  { "comfysage/aki" },
  { "ellisonleao/gruvbox.nvim", lazy = false },
  { "folke/tokyonight.nvim", lazy = false },
  { "mikesmithgh/gruvsquirrel.nvim" },
  { "nalexpear/spacegray.nvim" },
  { "rebelot/kanagawa.nvim", lazy = false },
  { "rose-pine/neovim", lazy = false },
  { "sainnhe/sonokai", lazy = false },
  { "sho-87/kanagawa-paper.nvim" },
  { "vague2k/vague.nvim" },
  { "projekt0n/github-nvim-theme", lazy = false, priority = 1000 },
  -- { "alexvzyl/nordic.nvim" },
  -- { "antonk52/lake.nvim" },
  -- { "behemothbucket/gruber-darker-theme.nvim" },
  -- { "carcuis/darcula.nvim" },
  -- { "delafthi/nord-nvim" },
  -- { "deparr/tairiki.nvim" },
  -- { "deviusvim/deviuspro.nvim" },
  -- { "echasnovski/mini.hues" },
  -- { "gbprod/nord.nvim" },
  -- { "gmr458/cold.nvim" },
  -- { "lewpoly/sherbet.nvim" },
  -- { "lfenzo/fusion.nvim" },
  -- { "lpuljic/nox-modus.nvim" },
  -- { "navarasu/onedark.nvim" },
  -- { "rmehri01/onenord.nvim" },
  -- { "samir-roy/shinjuku.nvim" },
  -- { "savq/melange-nvim" },
  -- { "shaunsingh/nord.nvim" },
  -- { "shawilly/ponokai" },
  -- { "starryleo/starry-vim-colorschemes" },
  -- { "steguiosaur/fullerene.nvim" },
  -- { "wittyjudge/gruvbox-material.nvim" },
  -- { "xiantang/darcula-dark.nvim" },
  -- { "zortax/three-firewatch" },

  -- Configure LazyVim to load my colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "gruvbox",
      -- colorscheme = "vscode",
      -- colorscheme = "catppuccin",
      -- colorscheme = "lunaperche",
      colorscheme = "slate",
      -- colorscheme = "sonokai",
    },
  },
  {
    "zaldih/themery.nvim",
    lazy = false,
    config = function()
      require("themery").setup({
        themes = vim.fn.getcompletion("", "color"),
      })
    end,
  },
}
